language: python 
rvm: 
  - 3.5
before_script: 
  - pip install python-coveralls
  - pip install coverage
  - pip install nose
  - pip install colorize
script: 
  - nosetests --with-coverage 
  - make test
after_success: 
  - coveralls
